### ISSUE TITLE
Updating Blacklight

### ISSUE THREAD

**Issue by nikhilro** [castorini/gooselight2#3]
Is there some reasonable way to update our `blacklight` with it's head? 

I noticed that they updated the [the shared views](https://github.com/projectblacklight/blacklight/tree/master/app/views/shared) which provides more customization capability?

We can close this issue if not. @edwinzhng @lintool?

**Comment by nikhilro** [comment]
I guess we just need to update the requirements in Gemfile whenever we want to "upgrade"

**Comment by edwinzhng** [comment]
We're at the latest version, I overrode the shared views entirely for the ACL header and footer because they're mostly different
